.travis.yml, CHANGELOG.md, composer.json
This fixes the TYPO3 installation process using Composer on Travis
both for 7.6 as well as 8.7.
=> [BUGFIX] Require typo3/minimal for installing TYPO3

.travis.yml, CHANGELOG.md, composer.json
This makes it possible to have different test runners in TYPO3 7.6
and 8.7.
=> [TASK] Make the PHPUnit test runner configurable

CHANGELOG.md, Configuration/TypoScript/setup.txt
This works around a bug in mkforms.
=> [BUGFIX] Don't HTML-encode the data from the FE editor on saving

CHANGELOG.md, Classes/BackEnd/FlexForms.php
With TYPO3 8.7, this is now possible.
Fixes #76
=> [TASK] Use the EXT: notation for language files

.gitignore, CHANGELOG.md
This folder gets generated when running the tests in TYPO3 9LTS.
=> [BUGFIX] git-ignore the tests-generated var/log/ folder

CHANGELOG.md, Tests/Unit/FrontEnd/DefaultControllerTest.php, pi1/class.tx_onetimeaccount_pi1.php
=> [BUGFIX] Do not crash if no user groups are selected in the flexforms

CHANGELOG.md, composer.json, ext_emconf.php
Some extension do not provide all versions via the TER. Now the
dependency versions are relaxed so that installs in non-Composer systems
is possible in TYPO3 8.7 again.
=> [BUGFIX] Relax the dependencies to allow non-Composer installs again

CHANGELOG.md, composer.json
This allows running Composer plugins with Composer >= 2.2 when
developing this extension.
=> [TASK] Allow the development Composer plugins

.github/workflows/ci.yml
This avoids breakage due to type problems with TYPO3 8LTS.
=> [BUGFIX] Pin Composer on CI to version 2.2

Classes/Controller/AbstractUserController.php, Classes/Controller/UserWithAutologinController.php, Classes/Controller/UserWithoutAutologinController.php, Configuration/TCA/Overrides/sys_template.php, Configuration/TCA/Overrides/tt_content.php, Tests/Functional/HelloWorldTest.php, Tests/Unit/Controller/UserWithAutologinControllerTest.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php, composer.json, ext_emconf.php, ext_localconf.php
This fixes using locallang labels in Fluid without explicitly
having to provide the extension key.
=> [BUGFIX] Stop using CamelCase for the extension PHP namespace

Resources/Private/Partials/User.html
This allows the Extbase property mapper to actually convert the
provided string to a `DateTime` instance.
Fixes #248
=> [BUGFIX] Provide a date format for the birth date field

Classes/Controller/AbstractUserController.php, Classes/Service/CredentialsGenerator.php, Tests/Unit/Controller/UserWithAutologinControllerTest.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php, Tests/Unit/Service/CredentialsGeneratorTest.php
The generator will also be able to create a password next,
and hence needs a name that fits this purpose.
=> [TASK] Rename the username generator

Classes/Controller/AbstractUserController.php, Tests/Unit/Controller/UserWithAutologinControllerTest.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
When an FE login form is used that is on the same page as the
user creation form, a login must not lead to a crash even if it
is tried directy after a user has been created.
=> [BUGFIX] Fix crash when using the login form

Classes/Controller/AbstractUserController.php, Tests/Unit/Controller/UserWithAutologinControllerTest.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
This is required so that the created user then can be used for starting
a new user session.
=> [TASK] Explicitly persist the created user

Classes/Controller/AbstractUserController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/LoginStatus.html, Resources/Private/Templates/UserWithAutologin/Create.html, Resources/Private/Templates/UserWithoutAutologin/Create.html
Also stop displaying the credentials (which was a temporary measure
for manual testing).
Fixes #275
=> [FEATURE] Display an alert with the login status after user creation

Classes/Controller/AbstractUserController.php
This form needs to be able to receive incomplete objects and show
validation errors. To avoid redirect loops, we must not validate
the user model here.
Fixes #289
=> [BUGFIX] Skip validation for `newAction`

Tests/Functional/Service/AutologinTest.php, composer.json
Also remove redundant type annotations to fix PHPStan warnings.
=> [TASK] Update typo3/testing-framework

.github/workflows/ci.yml, .github/workflows/codecoverage.yml
This unblocks using the development version of TYPO3.
Fixes #377
=> [TASK] Require `typo3/cms-core` instead of `typo3/minimal` on CI

Tests/Functional/Validation/UserValidatorTest.php
This is in preparation for making the validation error messages localizable.
=> [TASK] Move the validator tests to functional tests

composer.json
Parallel testing breaks when we introduce abstract test classes for functional tests.
In addition, our functional test are so small that running them in parallel does not make much of a difference.
=> [TASK] Stop running the functional tests in parallel

Tests/Unit/Controller/UserWithAutologinControllerTest.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Starting with TYPO3 10LTS, controllers do not require any constructor parameters anymore.
Fixes #415
=> [CLEANUP] Simplify the mocks in the controller tests

CHANGELOG.md, Tests/Functional/Service/AutologinTest.php, Tests/Functional/Validation/UserValidatorTest.php
=> [BUGFIX] Stop using the deprecated `ObjectManager` in tests

.github/dependabot.yml
Dependabot will happily mangle them (like e.g., in #463).
=> [BUGFIX] Block Dependabot updates for multi-version dependencies

Classes/Controller/AbstractUserController.php, Tests/Unit/Controller/AbstractUserControllerTest.php
This makes testing a lot less of a hassle.
=> [TASK] Only assign non-empty user groups to the view

CHANGELOG.md, Classes/Controller/AbstractUserController.php, Tests/Unit/Controller/AbstractUserControllerTest.php, Tests/Unit/Controller/Fixtures/TestingQueryResult.php
Now, if the user group selector is hidden in the FE, or if no valid user groups are selected, the user will get all user groups from the configuration.
Fixes #419
=> [FEATURE] Add a fallback for the user groups

CHANGELOG.md, Classes/Configuration/FlexForms.php, Resources/Private/Partials/User.html
If the group selector is displayed, it should always be required (because optional radio buttons groups do not make sense).
In addition, it does not make sense to not display the user group selector if there is more than one user group to select from.
So make displaying the selector automatic depending on the number of available user groups, and have the radion buttons always required.
Fixes #476
=> [TASK] Make displaying the group selector non-configurable

CHANGELOG.md, Configuration/FlexForms/Plugin.xml
We don't need the suggest wizard in the flexforms, and it takes up vertical space.
Fixes #530
=> [TASK] Make the flexforms more compact by removing the wizards

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf
The official wording in the TYPO3 core has been "folder" for ages no, not "system folder" anymore.
Fixes #515
[ci skip]
=> [TASK] Improve the wording in a flexforms label

CHANGELOG.md, Classes/Service/CaptchaFactory.php, Classes/Validation/CaptchaValidator.php, Classes/Validation/UserValidator.php, Tests/Unit/Service/CaptchaFactoryTest.php, Tests/Unit/Validation/CaptchaValidatorTest.php, Tests/Unit/Validation/UserValidatorTest.php
This avoids warnings getting logged about non-singleton classes getting injected.
Fixes #627
=> [BUGFIX] Mark all injected classes as singletons

CHANGELOG.md, Classes/Service/CredentialsGenerator.php, Tests/Unit/Service/CredentialsGeneratorTest.php
This class is no Singleton, and trying to inject it causes a warning to get logged.
Fixes #622
=> [BUGFIX] Do not inject the `PasswordHashFactory`

CHANGELOG.md, Classes/Controller/AbstractUserController.php, Tests/Unit/Controller/AbstractUserControllerTest.php
This adds another safeguard against invalid input (instead of risking a DB error when inserting the data).
Fixes #620
=> [BUGFIX] Do not skip the Extbase property validations

CHANGELOG.md, Tests/Unit/Controller/AbstractUserControllerTest.php
Now the TYPO3 Core already provides the required functionality.
Fixes #711
=> [BUGFIX] Avoid the deprecated `CacheNullifyer::flushMakeInstanceCache`

.github/dependabot.yml
Now that we require TYPO3 >= 11 and PHP >= 7.4, we can allow some more updates.
=> [TASK] Drop obsolete blockers for Dependabot

Tests/Unit/Controller/UserWithoutAutologinControllerTest.php, Tests/Unit/Service/CaptchaFactoryTest.php, Tests/Unit/Service/CredentialsGeneratorTest.php, Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php
The native type for mocks should be the mocked type, not `MockObject`. This makes the intent of the code more clear.
=> [TASK] Use more expressive types in mocks

CHANGELOG.md, Tests/Functional/Validation/CaptchaValidatorTest.php, Tests/Functional/Validation/UserValidatorTest.php
The `LanguageService` is not available via DI in TYPO3 12LTS anymore.
Fixes #993
=> [BUGFIX] Use a factory for the `LanguageService` in the tests

CHANGELOG.md, Classes/Controller/UserWithoutAutologinController.php, Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
=> [BUGFIX] Avoid the deprecated `GeneralUtility::_POST()` and `::_GP()`

phpstan-baseline.neon, phpstan.neon
This removes one obstacle for upgrading to PHPStan 2.
Fixes #1037
=> [TASK] Allow `instanceOf` checks in a test in a different way

.github/dependabot.yml
There won't be a release 7.2.1.
=> [TASK] Move the Dependabot target milestone to 7.3.0
