.travis.yml
CHANGELOG.md

Also properly quote the PHP version string in the `.travis.yml`.

[BUGFIX] Enable MySQL on Travis CI

---

CHANGELOG.md
Classes/BackEnd/FlexForms.php
Configuration/FlexForms/FlexForms.xml
Tests/LegacyUnit/BackEnd/FlexFormsTest.php
Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Tests/LegacyUnit/FrontEnd/Fixtures/FakeDefaultController.php
composer.json

Also switch the dev autoloading to PSR-4.

[CLEANUP] Use CamelCase in the PHP namespace

---

CHANGELOG.md
composer.json

[CLEANUP] Drop surplus trailing slashes from Composer scripts

---

CHANGELOG.md
Configuration/TypoScript/Form.txt
Tests/Unit/FrontEnd/DefaultControllerTest.php
pi1/class.tx_onetimeaccount_pi1.php

[BUGFIX] Show the name label if first and last name are visible

---

CHANGELOG.md

[BUGFIX] Fix a typo in the changelog

---

CHANGELOG.md
composer.json

[BUGFIX] Add a dependency on typo3/cms-lang

---

Configuration/TypoScript/Form.txt
Tests/Unit/FrontEnd/DefaultControllerTest.php
pi1/class.tx_onetimeaccount_pi1.php

[BUGFIX] Allow an empty name if the field is hidden or non-required

---

.travis.yml
CHANGELOG.md
Classes/BackEnd/FlexForms.php
Classes/ConfigCheck.php
Configuration/php-cs-fixer.php
Tests/Functional/FrontEnd/DefaultControllerTest.php
Tests/Unit/BackEnd/FlexFormsTest.php
Tests/Unit/FrontEnd/DefaultControllerTest.php
Tests/Unit/FrontEnd/Fixtures/FakeDefaultController.php
composer.json
phpcs.xml.dist
pi1/class.tx_onetimeaccount_pi1.php

[FEATURE] Add PHP sniffing and fixing

---

CHANGELOG.md
composer.json
ext_emconf.php

Also update the recommendations for adding FE user fields.

[TASK] Bump the static_info_tables dependency

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php
composer.json
ext_emconf.php
pi1/class.tx_onetimeaccount_pi1.php

[TASK] Use the new configuration check

---

CHANGELOG.md
composer.json
ext_emconf.php

This fixes some issues with TYPO3 9LTS.

[TASK] Require oelib >= 3.0.3

---

CHANGELOG.md
Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php
Configuration/php-cs-fixer.php
composer.json

Now the `php:fix` Composer script runs `phpcbf` in addition to
`php-cs-fixer`.

[TASK] Improve the code autoformatting

---

CHANGELOG.md
Resources/Private/Templates/FrontEnd.html

[BUGFIX] Update the "for" attribute of labels

---

CHANGELOG.md
README.md
composer.json

[TASK] Switch the default branch from master to main

---

.github/workflows/release.yml
.travis.yml
CHANGELOG.md

[TASK] Switch the TER release from Travis CI to GitHub actions

---

Documentation/Screenshots/LiveExamples/Index.rst
README.md

[TASK] Link to the testing distribution

---

Configuration/TCA/Overrides/tt_content.php
ext_localconf.php

[BUGFIX] Fix the plugin registration in TYPO3 9LTS

---

.github/workflows/ci.yml
Configuration/TsLint.yml
composer.json

[FEATURE] Add TypoScript linting to the CI builds

---

Classes/Controller/AbstractUserController.php
Classes/Controller/UserWithAutologinController.php
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

This will help avoid code duplication.

[TASK] Add an abstract controller

---

Classes/Controller/AbstractUserController.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/nl.locallang.xlf
Resources/Private/Partials/User.html
Resources/Private/Templates/UserWithAutologin/New.html
Resources/Private/Templates/UserWithoutAutologin/New.html
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Add the initial user creation form

---

Resources/Private/Partials/User.html

This improves usability for the form.
Fixes #214

[TASK] Add input types and autocomplete attributes to the form

---

Classes/ViewHelpers/IsFieldEnabledViewHelper.php
Resources/Private/Partials/User.html
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php
composer.json

[FEATURE] Add a ViewHelper conditionally displaying fields

---

Classes/ViewHelpers/IsFieldEnabledViewHelper.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php

[TASK] Also check whether the ViewHelper argument is set at all

---

Resources/Private/Partials/User.html

[FEATURE] Hide/show the fields in the BE as configured

---

Classes/Controller/AbstractUserController.php
Resources/Private/Partials/User.html
Resources/Private/Templates/UserWithAutologin/New.html
Resources/Private/Templates/UserWithoutAutologin/New.html
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
ext_localconf.php

[FEATURE] Persist the user

---

Classes/ViewHelpers/IsFieldEnabledViewHelper.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php
phpstan-baseline.neon

This is helpful when debugging problems in the Fluid templates.

[BUGFIX] Check the ViewHelper arguments more thoroughly

---

Configuration/FlexForms/Plugin.xml

A form without any fields does not make much sense.
Fixes #252

[TASK] Require at least one field to get displayed

---

Classes/Controller/AbstractUserController.php
Configuration/FlexForms/Plugin.xml
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/it.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/nl.locallang.xlf
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Add a configuration for the PID for the created users

---

ext_localconf.php

[BUGFIX] Register the create action in TYPO3 V10 as well

---

Classes/Controller/AbstractUserController.php
Classes/Service/UsernameGenerator.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Service/UsernameGeneratorTest.php

[FEATURE] Add autogeneration for usernames

---

Configuration/FlexForms/Plugin.xml

We should keep the form as minimal as possible.

[TASK] Do not show thumbnails in the flexforms

---

Classes/Controller/AbstractUserController.php
Configuration/FlexForms/Plugin.xml
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/it.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/nl.locallang.xlf
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Add a configuration for the user groups

---

Classes/Controller/AbstractUserController.php
Classes/Service/CredentialsGenerator.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Service/CredentialsGeneratorTest.php
composer.json

[FEATURE] Add password generation

---

Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[CLEANUP] Align a field name in tests with a changed class name

---

Resources/Private/Partials/User.html
Resources/Private/Partials/ValidationResult.html

[FEATURE] Display the validation errors below the fields

---

Classes/Controller/AbstractUserController.php
Classes/Validation/UserValidator.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/ValidationResult.html
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Validation/UserValidatorTest.php

[FEATURE] Add and use a validator for the user model

---

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/User.html

Also fix a typo in a localized flash message.
Fixes #297

[TASK] Make the submit button label more specific

---

Tests/Functional/Service/AutologinTest.php
composer.json
ext_emconf.php

The oelib package is not used (yet).
Fixes #298

[TASK] Drop the oelib dependency

---

Documentation/Index.rst
README.md
Resources/Private/Partials/User.html

Also use Flex for aligning the submit button.
Fixes #282
Part of #231

[TASK] Upgrade the form to Bootstrap 5

---

Resources/Private/Partials/User.html

[TASK] Make better use of screen space in the form

---

Classes/Controller/AbstractUserController.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Automatically generate the full name from first and last name

---

Classes/Controller/AbstractUserController.php
Resources/Private/Partials/User.html
Resources/Private/Templates/UserWithAutologin/New.html
Resources/Private/Templates/UserWithoutAutologin/New.html
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Redirect after login to a provided redirect URL

---

Configuration/TCA/Overrides/tt_content.php

We'll make this plugin available again once it is finished
enough to be usable.
Fixes #217

[TASK] Disable the unfinished plugin without autologin

---

Documentation/Index.rst
Documentation/Installation.rst

[TASK] Document the installation process

---

Documentation/Index.rst
Documentation/Installation.rst
Documentation/Upgrading.rst

[TASK] Document the upgrade process

---

Configuration/TypoScript/constants.typoscript
Configuration/TypoScript/setup.typoscript

[CLEANUP] Drop the unused persistence settings from the TypoScript

---

.github/workflows/ci.yml
.github/workflows/publish.yml

[TASK] Upgrade the Ubuntu version for the GitHub CI runners

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml

[TASK] Switch CI to Composer 2.4

---

Configuration/FlexForms/Plugin.xml

[FEATURE] Provide defaults for the visible and required fields

---

Classes/Controller/UserWithoutAutologinController.php
Classes/Service/Autologin.php
Tests/Unit/Service/AutologinTest.php

Also make the method naming a bit more consistent.
Fixes #392

[CLEANUP] Use asserts for checking things we know are true

---

CHANGELOG.md
Resources/Private/Partials/User.html

Those match the lengths of the corresponding fields in the DB.
Fixes #288

[FEATURE] Add maxlength attributes to the HTML

---

CHANGELOG.md
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/it.locallang.xlf
Resources/Private/Language/nl.locallang.xlf

[FEATURE] Copy more labels from the old extension version

---

CHANGELOG.md
Classes/Validation/UserValidator.php
Resources/Private/Partials/ValidationResult.html
Tests/Functional/Validation/UserValidatorTest.php

[TASK] Move localized validation messages from partial to validator

---

CHANGELOG.md
Tests/Functional/Service/AutologinTest.php
Tests/Functional/Validation/UserValidatorTest.php
composer.json
ext_emconf.php

[TASK] Require oelib

---

CHANGELOG.md
Classes/Validation/UserValidator.php
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Tests/Functional/Validation/UserValidatorTest.php

[TASK] Switch to oelib's `AbstractConfigurationDependentValidator`

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php
Classes/ViewHelpers/ConfigurationCheckViewHelper.php
Resources/Private/Partials/ConfigurationCheck.html
Resources/Private/Templates/UserWithAutologin/New.html
Resources/Private/Templates/UserWithoutAutologin/New.html
Tests/Unit/Configuration/ConfigurationCheckTest.php
Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php
ext_conf_template.txt

[FEATURE] Add an automatic configuration check

---

.phpstorm.meta.php
composer.json

[BUGFIX] Also PHP-lint hidden files on CI

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Tests/Functional/Controller/AbstractUserControllerTest.php
Tests/Functional/Controller/Fixtures/XclassFrontendUser.php
Tests/Functional/Controller/UserWithAutologinControllerTest.php
Tests/Functional/Controller/UserWithoutAutologinControllerTest.php

[BUGFIX] Allow XCLASSing the FE user class

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require oelib >= 4.3.0

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Allow oelib 5.x

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require feuserextrafields >= 4.2.1

---

composer.json

[TASK] Raise the testing framework

---

Tests/Functional/Controller/AbstractUserControllerTest.php
Tests/Functional/Controller/UserWithoutAutologinControllerTest.php
Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Configuration/ConfigurationCheckTest.php
Tests/Unit/Configuration/FlexFormsTest.php
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Service/AutologinTest.php
Tests/Unit/Service/CredentialsGeneratorTest.php
Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php

[CLEANUP] Make fields in the tests private

---

CHANGELOG.md
Configuration/TCA/Overrides/tt_content.php
ext_localconf.php

[BUGFIX] Fix the plugin registration for TYPO3 10LTS/11LTS

---

CHANGELOG.md
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php
ext_localconf.php

[BUGFIX] Stop using the deprecated `TYPO3_MODE` constant

---

Tests/Functional/Service/AutologinTest.php

[BUGFIX] Build a proper fake frontend in the functional tests

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require feuserextrafields >= 5.2.0

---

.gitattributes
CHANGELOG.md
composer.json
rector.php

[FEATURE] Add a Rector configuration file

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require feuserextrafields >= 5.2.1

---

Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Validation/UserValidatorTest.php

[TASK] Move some validator tests to unit tests

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Classes/Validation/UserGroupValidator.php
Resources/Private/Partials/User.html
Tests/Functional/Validation/UserGroupValidatorTest.php
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Validation/UserGroupValidatorTest.php

[FEATURE] Add validation for the user group

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require oelib >= 5.0

---

.github/workflows/ci.yml

[TASK] Switch the code quality checks on CI to PHP 8.1

---

.github/workflows/ci.yml
CHANGELOG.md

[FEATURE] Add unit tests on 11LTS to the CI builds

---

.github/workflows/ci.yml
CHANGELOG.md

[FEATURE] Add functional tests on 11LTS to the CI builds

---

CHANGELOG.md
Configuration/Services.yaml

[FEATURE] Add a services configuration file

---

composer.json

This reverts commit 02c7bfc104a4de0f4df64280d1a8b19d45931339.
Fixes #417
Fixes #499

[TASK] Run the functional tests in parallel again

---

CHANGELOG.md
Tests/Unit/Controller/Fixtures/TestingQueryResult.php
phpstan-baseline.neon

[BUGFIX] Improve type safety in the tests

---

CHANGELOG.md
Tests/Unit/Service/CredentialsGeneratorTest.php

[TASK] Stop using Prophecy in the service tests

---

CHANGELOG.md
Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php

[TASK] Stop using Prophecy in the view helper tests

---

CHANGELOG.md
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[TASK] Stop using Prophecy in the controller tests

---

Tests/Unit/Validation/UserValidatorTest.php

[CLEANUP] Autoformat the code

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Tests/Unit/Controller/AbstractUserControllerTest.php

[TASK] Make the abstract classes `@internal`

---

CHANGELOG.md
ext_localconf.php

[TASK] Drop the 9TLS-only plugin element registration

---

CHANGELOG.md
Classes/Controller/UserWithAutologinController.php
Classes/Service/Autologin.php
Documentation/Installation.rst
Documentation/WhatDoesItDo.rst

[TASK] Deprecate the plugin with autologin

---

CHANGELOG.md
Classes/Validation/UserValidator.php

[TASK] Switch the user validator to recognize `DateTimeInterface`

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/User.html

[FEATURE] Add "diverse" option to the gender dropdown

---

README.md

[TASK] Reorder the TYPO3 version badges

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Classes/Domain/Model/Captcha.php
Classes/Service/CaptchaFactory.php
Classes/Validation/CaptchaValidator.php
Configuration/FlexForms/Plugin.xml
Documentation/WhatDoesItDo.rst
README.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/Captcha.html
Resources/Private/Partials/User.html
Resources/Private/Templates/UserWithAutologin/New.html
Resources/Private/Templates/UserWithoutAutologin/New.html
Tests/Functional/Validation/CaptchaValidatorTest.php
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Domain/Model/CaptchaTest.php
Tests/Unit/Service/CaptchaFactoryTest.php
Tests/Unit/Validation/CaptchaValidatorTest.php
phpstan-baseline.neon

[FEATURE] Add a CAPTCHA

---

composer.json

[TASK] Allow running PHP-CS-Fixer on PHP 8.2

---

CHANGELOG.md
Configuration/TCA/Overrides/tt_content.php

[TASK] Drop obsolete option from the plugin registration

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Tests/Unit/Controller/AbstractUserControllerTest.php

[FEATURE] Set the last login date when creating a FE user record

---

.github/workflows/ci.yml
composer.json

[TASK] Drop the JSON linting CI job

---

Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php

[CLEANUP] Use more stubs in the tests

---

Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php

We're calling methods with return values on it.

[TASK] Convert one stub into a mock back again

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf

[Task] Shorten the label for the salutation #412

[TASK] Shorten the label for the salutation #412

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/it.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/nl.locallang.xlf

[BUGFIX] Add `resname` to all language labels

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/fr.locallang.xlf
Resources/Private/Language/it.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/nl.locallang.xlf

[TASK] Unify the spelling of "email"

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Allow installations with oelib 6.x

---

Resources/Private/Language/locallang.xlf

Approving only applies to translations, not to the original English labels.
Fixes #778

[TASK] Drop `approved="yes"` from the English locallang files

---

CHANGELOG.md
Resources/Private/Language/locallang.xlf

[BUGFIX] Fix grammar in error message

---

.github/workflows/ci.yml
composer.json

[TASK] Also run PHP 8.2 with the lowest dependencies on CI

---

.gitattributes
.github/workflows/ci.yml
Build/bin/xliff-lint
composer.json

[TASK] Switch to the Symfony XLIFF linting

---

.github/workflows/ci.yml
composer.json
phive.xml

[TASK] Drop the copy'n'paste detection

---

CHANGELOG.md
Configuration/TypoScript/setup.typoscript
Resources/Private/Partials/User.html
Resources/Public/Css/FrontEnd.css

[BUGFIX] Improve accessibility of the form

---

.github/dependabot.yml
composer.json

[TASK] Drop the static_info_tables development dependency

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require `feuserextrafields` >= 6.2.0

---

composer.json

[TASK] Drop the `link-extensions` script from the `composer.json`

---

composer.json

[TASK] Drop `app-dir` from `composer.json`

---

.github/workflows/ci.yml

[TASK] Switch the code quality checks on CI to PHP 8.3

---

.github/dependabot.yml
composer.json

[TASK] Drop support for PHPUnit 7

---

composer.json
rector.php

[FEATURE] Add Rector

---

CHANGELOG.md
Classes/Controller/AbstractUserController.php
Classes/Domain/Model/Captcha.php
Classes/Service/CredentialsGenerator.php
Classes/Validation/CaptchaValidator.php
Tests/Functional/Service/AutologinTest.php
Tests/Functional/Validation/CaptchaValidatorTest.php
Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Configuration/ConfigurationCheckTest.php
Tests/Unit/Configuration/FlexFormsTest.php
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Controller/Fixtures/TestingQueryResult.php
Tests/Unit/Controller/UserWithAutologinControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Domain/Model/CaptchaTest.php
Tests/Unit/Service/AutologinTest.php
Tests/Unit/Service/CaptchaFactoryTest.php
Tests/Unit/Service/CredentialsGeneratorTest.php
Tests/Unit/Validation/CaptchaValidatorTest.php
Tests/Unit/Validation/UserValidatorTest.php
Tests/Unit/ViewHelpers/ConfigurationCheckViewHelperTest.php

[TASK] Use PHP 7.4 language features, add native type declarations

---

.github/dependabot.yml
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
Tests/Unit/Service/CaptchaFactoryTest.php
Tests/Unit/Service/CredentialsGeneratorTest.php
composer.json
phive.xml

[TASK] Upgrade to PHPUnit 9

---

.github/dependabot.yml
Tests/Functional/Service/AutologinTest.php
Tests/Functional/Validation/CaptchaValidatorTest.php
Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Controller/AbstractUserControllerTest.php
Tests/Unit/Service/CredentialsGeneratorTest.php
composer.json

[TASK] Upgrade to typo3/testing-framework V7

---

composer.json

[TASK] Remove the workaround for PHP-CS-Fixer on PHP 8.2

---

.github/workflows/codecoverage.yml

[TASK] Switch the code coverage CI job to PHP 8.3

---

Tests/Functional/Service/AutologinTest.php
Tests/Functional/Validation/CaptchaValidatorTest.php
Tests/Functional/Validation/UserValidatorTest.php

[CLEANUP] Use the Composer keys for dependencies in functionals

---

Tests/Unit/Controller/Fixtures/TestingQueryResult.php
phpstan-baseline.neon

[TASK] Harden a fixture class

---

rector.php

[TASK] Update the Rector configuration

---

.github/workflows/automerge.yml
.github/workflows/ci.yml
.github/workflows/codecoverage.yml
.github/workflows/publish.yml

[TASK] Switch the Ubuntu CI runners to 24.04

---

CHANGELOG.md
Classes/Service/CredentialsGenerator.php
Tests/Unit/Service/CredentialsGeneratorTest.php

[TASK] Switch `CredentialsGenerator` to constructor injection

---

CHANGELOG.md
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[TASK] Switch the controller to constructor DI

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Require `feuserextrafields` >= 6.3.0

---

CHANGELOG.md
Classes/Configuration/FlexForms.php
Classes/Validation/UserValidator.php
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/User.html
Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Configuration/FlexFormsTest.php
Tests/Unit/Validation/UserValidatorTest.php

[FEATURE] Add a checkbox for the terms and conditions

---

Configuration/FlexForms/Plugin.xml
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/User.html

[FEATURE] Add a setting for the terms & conditions page

---

CHANGELOG.md
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[FEATURE] Record the date of acceptance for the terms and privacy

---

CHANGELOG.md
Classes/Configuration/FlexForms.php
Classes/Validation/UserValidator.php
Resources/Private/Language/locallang.xlf
Resources/Private/Partials/User.html
Tests/Functional/Validation/UserValidatorTest.php
Tests/Unit/Configuration/FlexFormsTest.php
Tests/Unit/Validation/UserValidatorTest.php

[FEATURE] Add a field for the VAT IN

---

CHANGELOG.md
README.md

[TASK] Drop the 10LTS badge from the README

---

README.md

[TASK] Remove the download counter from the README

---

CHANGELOG.md
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php

[BUGFIX] Avoid using the deprecated `$GLOBALS['TSFE']->fe_user`

---

composer.json

[TASK] Drop unnecessary `.Build/vendor/bin/` from Composer scripts

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php

[TASK] Mark some classes and methods as `@internal`

---

CHANGELOG.md
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
composer.json

[BUGFIX] Always return a response from the actions

---

CHANGELOG.md
composer.json
ext_emconf.php

Also require the bugfix version 6.0.1.

[TASK] Require oelib >= 6.0

---

.github/workflows/ci.yml
CHANGELOG.md

[TASK] Also run the functional tests with 12LTS

---

.github/workflows/ci.yml
CHANGELOG.md

[TASK] Also run the unit tests with 12LTS

---

.github/workflows/codecoverage.yml

[TASK] Switch the code coverage generation to TYPO3 12LTS

---

CHANGELOG.md
Classes/Controller/UserWithoutAutologinController.php
Tests/Unit/Controller/UserWithoutAutologinControllerTest.php
phpstan-baseline.neon

[BUGFIX] Fix the redirect response with TYPO3 12LTS

---

composer.json

This fixes some issues with PHP 8.4.

[TASK] Update the Symfony development dependencies

---

phpstan.neon

[TASK] Also check `ext_localconf.php` with PHPStan

---

.github/workflows/ci.yml

[TASK] Add a CI job for rendering/checking the documentation

---

CHANGELOG.md
composer.json

[TASK] Allow `typo3fluid/fluid:^4.0`

---

composer.json
phpstan.neon

[TASK] Add the Rector Type Perfect PHPStan rules

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml
.github/workflows/publish.yml

In this case, we don't need to quote the strings.
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

[CLEANUP] Do not quote workflow/job names for GitHub actions
